using AutoMapper;
using PatientManagement.Data;
using PatientManagement.Models;

namespace PatientManagement.Mapping
{
    public class PatientProfile : Profile
    {
        public PatientProfile()
        {
            // Map from PatientModel (DTO) to Patient (Entity)
            CreateMap<PatientModel, Patient>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())              // Id is generated by DB
                .ForMember(dest => dest.CreateDate, opt => opt.Ignore())      // Set manually on creation
                .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore());    // Set manually when updating

            // Map from Patient (Entity) to PatientModel (DTO)
            CreateMap<Patient, PatientModel>();
        }
    }
}
